// Root folders for the file navigator
export default [
  {
    id: 'root-1',
    name: 'mindcraft.chronicles',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.chronicles',
    indent: 0,
    _opened: true,
  },
  {
    id: 'root-2',
    name: 'mindcraft.nodes',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.nodes',
    indent: 0,
    _opened: false,
  },
  {
    id: 'root-3',
    name: 'mindcraft.protocols',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.protocols',
    indent: 0,
    _opened: false,
  },
  {
    id: 'root-4',
    name: 'mindcraft.garage',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.garage',
    indent: 0,
    _opened: false,
  },
  {
    id: 'root-5',
    name: 'mindcraft.oss',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.oss',
    indent: 0,
    _opened: false,
  },
  {
    id: 'root-6',
    name: 'mindcraft.servers',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.servers',
    indent: 0,
    _opened: false,
  },
  {
    id: 'root-7',
    name: 'mindcraft.ui',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.ui',
    indent: 0,
    _opened: false,
  },
]
