// Root folders for the file navigator
export default [
  {
    id: BigInt(10),
    name: 'mindcraft.nodes',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.nodes',
    indent: 0,
    _opened: true,
  },
  {
    id: BigInt(20),
    name: 'mindcraft.protocols',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.protocols',
    indent: 0,
    _opened: false,
  },
  {
    id: BigInt(30),
    name: 'mindcraft.garage',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.garage',
    indent: 0,
    _opened: false,
  },
  {
    id: BigInt(40),
    name: 'mindcraft.oss',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.oss',
    indent: 0,
    _opened: false,
  },
  {
    id: BigInt(50),
    name: 'mindcraft.ui',
    type: 'folder',
    icon: 'nodes/folder',
    path: '/',
    caption: '~/Workspace/starvale.io/mindcraft.ui',
    indent: 0,
    _opened: false,
  },
]
